---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: examiner
  namespace: apps
spec:
  imageRepositoryRef:
    name: examiner
  policy:
    semver:
      range: "1.10.1"
